name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Describe current revision with tags
        run: git describe --tags --dirty
      - name: Install Ruby
        uses: actions/setup-ruby@v1
      - name: Install NuGet
        uses: nuget/setup-nuget@v1
      - name: Install Gems
        run: bundle install
      - name: Install NuGet packages
        run: nuget restore
      - name: Set KSP Version
        run: |
          echo "::set-env name=KSP_VERSION::$(cat KSP_VERSION)"
          echo "${KSP_VERSION}"
      - name: Download KSP DLLs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DLL_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DLL_S3_SECRET_ACCESS_KEY }}
        run: aws s3 cp s3://blowfish-ksp-dlls/ksp-${{ env.KSP_VERSION }}.zip '/tmp/KSP_DLLs.zip'
      - name: Set KSP DLL path
        run: echo "::set-env name=KSP_DLL_PATH::/opt/ksp/assembly/${KSP_VERSION}"
      - name: Extract KSP DLLs
        run: |
          mkdir -p "${KSP_DLL_PATH}"
          unzip '/tmp/KSP_DLLs.zip' -d "${KSP_DLL_PATH}"
          rm '/tmp/KSP_DLLs.zip'
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Compile Project
        run: msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" B9PartSwitch.sln
      - name: Run Unit Tests
        run: mono packages/xunit.runner.console.*/tools/net471/xunit.console.exe B9PartSwitchTests/bin/Release/B9PartSwitchTests.dll
      - name: Extract Changelog
        run: |
          curl 'https://raw.githubusercontent.com/wiki/blowfishpro/B9PartSwitch/Changelog.md' -o "${RUNNER_TEMP}/B9PartSwitch-Changelog-all.md"
          bundle exec extract-changelog -u "$(git describe --tags)" -i "${RUNNER_TEMP}/B9PartSwitch-Changelog-all.md" -o "${RUNNER_TEMP}/B9PartSwitch-Changelog-current.md"
      - name: Set release directory
        run: |
          RELEASE_DIR="${RUNNER_TEMP}/release"
          echo "Release dir: ${RELEASE_DIR}"
          mkdir -v "${RELEASE_DIR}"
          echo "::set-env name=RELEASE_DIR::${RELEASE_DIR}"
      - name: Assemble Release
        run: |
          cp -v -R "${GITHUB_WORKSPACE}/GameData" "${RELEASE_DIR}"
          cp -v "${GITHUB_WORKSPACE}/README.md" "${RELEASE_DIR}"
          cp -v "${GITHUB_WORKSPACE}/LICENSE" "${RELEASE_DIR}"
          cp -v "${RUNNER_TEMP}/B9PartSwitch-Changelog-current.md" "${RELEASE_DIR}/CHANGELOG.md"
          cp -v "${GITHUB_WORKSPACE}/README.md" "${RELEASE_DIR}/GameData/B9PartSwitch"
          cp -v "${GITHUB_WORKSPACE}/LICENSE" "${RELEASE_DIR}/GameData/B9PartSwitch"
          cp -v "${RUNNER_TEMP}/B9PartSwitch-Changelog-current.md" "${RELEASE_DIR}/GameData/B9PartSwitch/CHANGELOG.md"
          "${GITHUB_WORKSPACE}/bin/fill-version" "${GITHUB_WORKSPACE}/templates/B9PartSwitch.version.erb" "${RELEASE_DIR}/GameData/B9PartSwitch/B9PartSwitch.version"
      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: B9PartSwitch.zip
          path: ${{ env.RELEASE_DIR }}
      - name: Verify result
        run: bundle exec rake spec
