name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - run: echo "::set-env name=KSP_VERSION::$(cat KSP_VERSION)"
      - run: echo "${KSP_VERSION}"
      - run: sudo apt-get install nuget
      - name: Download KSP DLLs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DLL_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DLL_S3_SECRET_ACCESS_KEY }}
        run: aws s3 cp s3://blowfish-ksp-dlls/ksp-${{ env.KSP_VERSION }}.zip '/tmp/KSP_DLLs.zip'
      - name: Extract KSP DLLs
        run: |
          mkdir -p "/opt/ksp/assembly/${KSP_VERSION}"
          unzip '/tmp/KSP_DLLs.zip' -d "/opt/ksp/assembly/${KSP_VERSION}"
          rm '/tmp/KSP_DLLs.zip'
      - name: Install Gems
        run: bundle install
      - name: Run Rubocop
        run: bundle exec rubocop
